### PR TITLE
internal: split and clean up

### LINKED ISSUE #128: internal: break package into conceptually related types and functions
At the moment it's a grab bag of things. It could be broken into set, ~~sortutils~~ ordered (picking up some copied types distributed throughout the repo), and linear.

### PR DESCRIPTION
**Pull request by kortschak**
Fixes #128.

@vladimir-ch Please take a look.

### CODE REVIEW

File: path/control_flow.go [hunk 1]
```diff
@@ -6,17 +6,17 @@ package path
...
+	"github.com/gonum/graph/internal/set"
 )
 
 // PostDominatores returns all dominators for all nodes in g. It does not
 // prune for strict post-dominators, immediate dominators etc.
 //
 // A dominates B if and only if the only path through B travels through A.
-func Dominators(start graph.Node, g graph.Graph) map[int]internal.Set {
-	allNodes := make(internal.Set)
+func Dominators(start graph.Node, g graph.Graph) map[int]set.Nodes {
```
Comment (kortschak) [inline path/control_flow.go]: This and below touches an outstanding issue, that clients don't have access to the documentation of set.Nodes because it is internal. They can get the information, out of the value though.

Just commenting here to note that I am aware of the issue, but it's not a high priority since no-one has complained.

File: topo/common_test.go [hunk 2]
```diff
@@ -32,14 +32,14 @@ var batageljZaversnikGraph = []set{
 	20: nil,
 }
 
-// set is an integer set.
-type set map[int]struct{}
+// intset is an integer set.
```
Comment (vladimir-ch) [inline topo/common_test.go]: What's the difference between this and set.Ints?

Comment (kortschak) [inline topo/common_test.go]: Yeah, I was thinking about rolling that in, but I don't want to expose linksTo. set here is really an edge list entry set.

Comment (vladimir-ch) [inline topo/common_test.go]: Ok

**Comment by vladimir-ch** [comment]
LGTM
